import { JobPosting, Recruiter, FraudAlert, User } from "./types";

export const DEMO_USERS: Record<string, { password: string; user: User }> = {
  Admin: {
    password: "123",
    user: { username: "Admin", role: "admin", name: "Admin Panel" },
  },
  "stud@123": {
    password: "12345",
    user: { username: "stud@123", role: "student", name: "Rahul Sharma" },
  },
};

export const recruiters: Recruiter[] = [
  {
    id: "r1",
    companyName: "Google India",
    domain: "google.com",
    verified: true,
    trustLevel: "high",
    rating: 4.9,
    totalReviews: 234,
    logo: "🏢",
    verifiedAt: "2025-12-01",
  },
  {
    id: "r2",
    companyName: "Microsoft",
    domain: "microsoft.com",
    verified: true,
    trustLevel: "high",
    rating: 4.8,
    totalReviews: 189,
    logo: "🏢",
    verifiedAt: "2025-11-15",
  },
  {
    id: "r3",
    companyName: "Infosys",
    domain: "infosys.com",
    verified: true,
    trustLevel: "medium",
    rating: 4.2,
    totalReviews: 156,
    logo: "🏢",
    verifiedAt: "2025-10-20",
  },
  {
    id: "r4",
    companyName: "TechStart Solutions",
    domain: "techstart.io",
    verified: false,
    trustLevel: "low",
    rating: 2.1,
    totalReviews: 12,
    logo: "🏢",
  },
  {
    id: "r5",
    companyName: "Wipro",
    domain: "wipro.com",
    verified: true,
    trustLevel: "high",
    rating: 4.5,
    totalReviews: 201,
    logo: "🏢",
    verifiedAt: "2025-09-10",
  },
  {
    id: "r6",
    companyName: "QuickJobs Corp",
    domain: "quickjobs.xyz",
    verified: false,
    trustLevel: "unverified",
    rating: 1.2,
    totalReviews: 3,
    logo: "🏢",
  },
];

export const jobPostings: JobPosting[] = [
  {
    id: "j1",
    title: "Software Engineer - Full Stack",
    company: "Google India",
    recruiterId: "r1",
    type: "job",
    location: "Bangalore, India",
    salary: "₹25-40 LPA",
    description: "Join Google's engineering team to build world-class products that impact billions of users worldwide.",
    requirements: ["B.Tech/M.Tech in CS", "3+ years experience", "React, Node.js, Python"],
    postedAt: "2026-02-05",
    trustScore: 98,
    verified: true,
    flagged: false,
    applicationUrl: "https://careers.google.com",
    recruiter: recruiters[0],
  },
  {
    id: "j2",
    title: "Data Science Intern",
    company: "Microsoft",
    recruiterId: "r2",
    type: "internship",
    location: "Hyderabad, India",
    salary: "₹50,000/month",
    description: "Work with Microsoft's AI research team on cutting-edge machine learning projects.",
    requirements: ["Pursuing B.Tech/M.Tech", "Python, ML basics", "Strong analytical skills"],
    postedAt: "2026-02-03",
    trustScore: 96,
    verified: true,
    flagged: false,
    applicationUrl: "https://careers.microsoft.com",
    recruiter: recruiters[1],
  },
  {
    id: "j3",
    title: "Associate Software Engineer",
    company: "Infosys",
    recruiterId: "r3",
    type: "job",
    location: "Pune, India",
    salary: "₹6-10 LPA",
    description: "Join Infosys as a fresher and kickstart your IT career with training and mentorship.",
    requirements: ["B.Tech in any branch", "Good communication", "Willingness to learn"],
    postedAt: "2026-02-01",
    trustScore: 82,
    verified: true,
    flagged: false,
    applicationUrl: "https://careers.infosys.com",
    recruiter: recruiters[2],
  },
  {
    id: "j4",
    title: "Marketing Intern - URGENT HIRING $$",
    company: "TechStart Solutions",
    recruiterId: "r4",
    type: "internship",
    location: "Remote",
    salary: "₹1,00,000/month + iPhone",
    description: "Earn big money from home! No experience needed. Just pay a small registration fee of ₹5000 to get started.",
    requirements: ["No experience needed", "Pay registration fee"],
    postedAt: "2026-02-07",
    trustScore: 12,
    verified: false,
    flagged: true,
    flagReason: "Scam keywords detected: 'registration fee', unrealistic salary, urgency tactics",
    applicationUrl: "#",
    recruiter: recruiters[3],
  },
  {
    id: "j5",
    title: "Cloud Engineer",
    company: "Wipro",
    recruiterId: "r5",
    type: "job",
    location: "Chennai, India",
    salary: "₹8-15 LPA",
    description: "Design and manage cloud infrastructure for enterprise clients using AWS and Azure.",
    requirements: ["B.Tech in CS/IT", "AWS/Azure certified", "2+ years experience"],
    postedAt: "2026-01-28",
    trustScore: 90,
    verified: true,
    flagged: false,
    applicationUrl: "https://careers.wipro.com",
    recruiter: recruiters[4],
  },
  {
    id: "j6",
    title: "Work From Home - Earn ₹50K Daily!!!",
    company: "QuickJobs Corp",
    recruiterId: "r6",
    type: "job",
    location: "Remote",
    salary: "₹50,000/day",
    description: "Easy money! Click links and earn. Send your bank details to start immediately.",
    requirements: ["Phone with internet", "Bank account details"],
    postedAt: "2026-02-08",
    trustScore: 5,
    verified: false,
    flagged: true,
    flagReason: "Multiple fraud indicators: unrealistic pay, request for bank details, suspicious domain",
    applicationUrl: "#",
    recruiter: recruiters[5],
  },
];

export const fraudAlerts: FraudAlert[] = [
  {
    id: "f1",
    postingId: "j4",
    reason: "Registration fee required — common scam pattern detected",
    severity: "high",
    timestamp: "2026-02-07T14:30:00",
    resolved: false,
  },
  {
    id: "f2",
    postingId: "j6",
    reason: "Request for bank details and unrealistic daily pay of ₹50,000",
    severity: "high",
    timestamp: "2026-02-08T09:15:00",
    resolved: false,
  },
  {
    id: "f3",
    postingId: "j4",
    reason: "Unverified company domain: techstart.io — no business records found",
    severity: "medium",
    timestamp: "2026-02-07T14:32:00",
    resolved: false,
  },
];
